### ISSUE TITLE
部署后登录报错Invalid APP Code [bk_app_code=bk_paas], please confirm if the APP Code has been registered

### ISSUE THREAD

**Issue by gdnotepad** [Tencent/bk-PaaS#1003]
版本:bk-PaaS-ft_upgrade_py3以及2.14.14
部署完成后，登录报错
Invalid APP Code [bk_app_code=bk_paas], please confirm if the APP Code has been registered
login.log:ERROR [2022-06-15 19:25:43] /usr/local/src/bk-PaaS-ft_upgrade_py3/paas2/login/components/esb.py 69 _call_esb_api 28147 140450600639304
call esb api error! http_post http://new-paas.bitmartpro.com/api/c/compapi/v1/usermanage/login/check/, data: {'username': 'admin', 'password': 'Bit******', 'bk_app_code': 'bk_paas', 'bk_app_secret': 'ffe******', 'bk_username': 'admin', 'app_code': 'bk_paas', 'app_secret': 'ffe******'}, code: 1306000, message: Invalid APP Code [bk_app_code=bk_paas], please confirm if the APP Code has been registered

paas,esb,appengine无相关日志

**Comment by gdnotepad** [comment]
login.log:ERROR [2022-06-15 19:25:43] /usr/local/src/bk-PaaS-ft_upgrade_py3/paas2/login/components/esb.py 69 _call_esb_api 28147 140450600639304
 	 call esb api error! http_post http://new-paas.bitmartpro.com/api/c/compapi/v1/usermanage/login/check/, data: {'username': 'admin', 'password': 'Bit******', 'bk_app_code': 'bk_paas', 'bk_app_secret': 'ffe******', 'bk_username': 'admin', 'app_code': 'bk_paas', 'app_secret': 'ffe******'}, code: 1306000, message: Invalid APP Code [bk_app_code=bk_paas], please confirm if the APP Code has been registered

paas,esb,appengine无相关日志

**Comment by wklken** [comment]
部署后, 需要将bk_paas写入白名单(如果使用的蓝鲸部署套件, 部署脚本会自动写入)

对应表: open_paas.esb_app_account
