### ISSUE TITLE
节点管理 nginx server配置保存异常

### ISSUE THREAD

**Issue by jefffffffffffffffff** [Tencent/bk-PaaS#104]
bk完整app版本号:5.0.4
部署方式:单机完全安装
部署配置:16c32g500g
异常app:【bk_nodeman】
异常app部署版本号:bk_nodeman_V1.1.12
异常问题: 
问题1:
1. 节点管理,右上角点击 nginx serever 配置,填写ip:port 点击保存报错,错误如下:
![image](https://user-images.githubusercontent.com/12181410/56859422-2f036d80-69bd-11e9-83ca-d3c1597e6979.png)
2. 基于1咨询了QQ群给我答复是未填写耗时时间导致,继续填写超时时间后点击保存,依然报错;
3. 基于2继续咨询QQ群给我答复是没有点击立即配置,继续点击立即配置,依然报错;

问题2:
1. 业务列表展示了已经停用了的业务名称"蓝鲸",该业务在配置管理平台状态为停用;
![image](https://user-images.githubusercontent.com/12181410/56859536-18f6ac80-69bf-11e9-8a9b-7ec5cc6b9fec.png)

个人分析:
问题1和2,应该是bug导致.

**Comment by wklken** [comment]
@jefffffffffffffffff jef

请到 https://bk.tencent.com/s-mart/community/ 论坛发帖, 会得到相关的支持和协助;

bk-PaaS 只维护蓝鲸智云PaaS开源版相关的bug及feature;  对应SaaS的issue请到蓝鲸对应SaaS开源的issues下提issue(如果对应SaaS未开源, 请到论坛发帖或者对应支持群寻求解决方案); Close;
