### ISSUE TITLE
调用企业微信API， 状态码返回是200， 返回的内容是报错！

### ISSUE THREAD

**Issue by GJDevil** [Tencent/bk-PaaS#107]
调用企业微信API接口， 返回的status_code是200， 但是content返回的内容是有问题的，错误的信息如下：
{‘message’： “Component request third-party system [weixin_qy] error: [get_token] error: status_code: 404, Error Message: Third-party system does not find this interface”}

**Comment by wklken** [comment]
这里返回的内容表示: esb请求第三方接口404;  即esb请求`system= weixin_qy`的`get_token`对应的地址404; 需要确认 1) 配置接入了企业微信API , 存在对应的system 2) get_token存在且地址正确
