### ISSUE TITLE
企业级Java开发环境搭建 框架无法正常运行 mavenInstall mavenClean报错

### ISSUE THREAD

**Issue by gyc573506962** [Tencent/bk-PaaS#109]
![图片1](https://user-images.githubusercontent.com/31149558/57497142-00648b80-7309-11e9-9259-e311021bc82e.png)

mavenUpdate的时候不会报错不会报错但是mavenInstall 或者mavenClean的时候会报下面这个错误

![image](https://user-images.githubusercontent.com/31149558/57497164-140ff200-7309-11e9-8750-c1a1f8369427.png)
![image](https://user-images.githubusercontent.com/31149558/57497171-15d9b580-7309-11e9-9842-145c2e45e1fe.png)
![image](https://user-images.githubusercontent.com/31149558/57497175-1d995a00-7309-11e9-9163-ac6e2c6b596a.png)
![image](https://user-images.githubusercontent.com/31149558/57497176-1eca8700-7309-11e9-94d3-f77bfbed63ad.png)

mavenClean也是一样的
![image](https://user-images.githubusercontent.com/31149558/57497180-212ce100-7309-11e9-966f-1cdac0a87119.png)
![image](https://user-images.githubusercontent.com/31149558/57497184-238f3b00-7309-11e9-8063-3f6c447ebf0f.png)

而且BkWebApplication.java进行项目启动的时候run as什么都没有
![image](https://user-images.githubusercontent.com/31149558/57497199-39046500-7309-11e9-9b1f-84bdc8aea3ae.png)

内网进行mavenUpdate  或者项目导入时会报这个错误
![image](https://user-images.githubusercontent.com/31149558/57497201-3c97ec00-7309-11e9-9676-27847dd25fdd.png)

**Comment by wklken** [comment]
您咨询的问题非“社区版PaaS平台”开源项目，请前往腾讯蓝鲸问答社区获取建议与帮助。

问答社区入口：https://bk.tencent.com/s-mart/community

说明：企业版相关的问题，以企业内负责实施的服务提供商为主要技术支持方，若得不到有效的技术支持，可发邮件到contactus_bk@tencent.com咨询腾讯蓝鲸官方获取建议。

感谢对蓝鲸的支持与理解。
