### ISSUE TITLE
登录页面只输入用户，点击登录后跳转到异常页面

### ISSUE THREAD

**Issue by linxiaowu-canway** [Tencent/bk-PaaS#1105]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
是BUG

**PaaS/PaaSAgent版本(The versions used):**
2.14.44

**发生了什么(What happened):**
登录页面只输入随意用户，点击登录
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/f27350b4-20cd-4030-8982-383b6bd5a1b2)
跳转到异常页面，而非提示“账户或者密码错误，请重新输入”
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/8decad0a-174e-4a08-8d9c-29c8c0e208a4)

**期望是什么(What you expected to happen):**
提示“账户或者密码错误，请重新输入”
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/49e5e2a2-195d-4571-86fb-1c490d20b0be)

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by linxiaowu1992** [comment]
在2.14.44，开启了登录加密，点击登录后，前端进行了密码加密，即使没有输入密码，也会作为空字符串进行加密后传递到后端：
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/3218f658-d405-42c0-a2a7-8980b80fe5a8)
后端BkAuthenticationForm解密后password为空，不进入authenticate：
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/72b6f2b8-0063-42af-9d57-6f7824b697ab)

修复方式：
将解密两行代码，放置到条件分支代码中：
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/32337623-a5fd-4a23-a038-4e57607c736c)

**Comment by wklken** [comment]
提个pr

**Comment by linxiaowu1992** [comment]
>= 2.14.61修复
