### ISSUE TITLE
开源的PAAS平台中怎么添加开源的CMDB？

### ISSUE THREAD

**Issue by Hylijia** [Tencent/bk-PaaS#111]
#####  PAAS平台中如何接入CMDB

  开源的PAAS登入后什么服务也没有，对之前蓝鲸开源过的CMDB没有登入功能，是否可以和PAAS结合起来使用，实现统一登入。

**Comment by wklken** [comment]
- paas配置文件中配置了 `settings.HOST_CC` / `settings.HOST_JOB` 之后, 用户登录后, 在首页面板可以看到cc/job入口;
- 如果一开始没有配置, 使用管理员登录后看不到, 后续即使配置了, 之前登录过的用户也看不到(第一次登录时初始化了), 只有新用户可见; 此时如果成本不高, 可以保证配置了`HOST_CC/HOST_JOB`前提下, 清库重新migration
- 具体逻辑见`paas/home/utils.py`

---------

- cmdb可以在启动时通过`--blueking_paas_url`配置paas的地址, 具体可以咨询cmdb, [相关文档](https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md)
