### ISSUE TITLE
单独部署的paas以及cmdb，使用paas跳转cmdb后跳转回用户管理页面

### ISSUE THREAD

**Issue by yangbojun** [Tencent/bk-PaaS#112]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**PaaS/PaaSAgent版本(The versions used):**
PaaS 3.2.2

**发生了什么(What happened):**
![image](https://user-images.githubusercontent.com/49931460/57749123-5d987c80-770f-11e9-82a2-5ff266368b3e.png)
点击关联的cmdb，可以正常跳转到login页面
![image](https://user-images.githubusercontent.com/49931460/57749167-8d478480-770f-11e9-9f54-6e9b4519f3a5.png)
输入用户名密码后直接跳转到了用户管理页面
![image](https://user-images.githubusercontent.com/49931460/57749221-c1bb4080-770f-11e9-94b3-69f3fdc02e71.png)
直接登陆cmdb的页面与上述操作结果一样
可以正常跳转到paas的login页面，输入用户密码后跳转用户管理页面
cmdb_webserver配置如下
![image](https://user-images.githubusercontent.com/49931460/57749341-32faf380-7710-11e9-8870-7c6552985fca.png)

**期望是什么(What you expected to happen):**
希望登陆后可以正常跳转回cmdb页面

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
发生了什么, 这一步中 `登录页面` 的url地址是什么? 
(默认url地址中带了c_url是登录成功之后跳转的地址, 例如`/login/?c_url=/app/list`)

**Comment by yangbojun** [comment]
返回的ip是这个http://www.bking.com/login/?app_id=bk_cmdb&c_url=http://127.0.0.1:8083/

在cmdb的cmdb_webserver.conf配置的

**Comment by yangbojun** [comment]
简单来说就是我用cmdb调用paas的login页面实现用户登陆，但是调用到paas的login页面后输入用户名密码都会跳转到paas的用户管理页面

**Comment by wklken** [comment]
- cmdb和paas是通过 cookie 共享登录态的, 所以其`必须使用相同的一级域名`, cmdb会取请求的cookie中的登录态, 发往paas进行登录态校验, 校验失败跳转到登录页面
- 假设给cmdb配置 cmdb.bking.com, 才能正确跳转 `c_url=http://cmdb.bking.com/`
