### ISSUE TITLE
服务器信息 & 第三方服务管理列表，操作icon建议加tooltips提示 

### ISSUE THREAD

**Issue by sundytt** [Tencent/bk-PaaS#132]
![image](https://user-images.githubusercontent.com/30256396/58252487-cf6c6800-7d98-11e9-9c6e-7b431e8d88f1.png)

**Comment by chainingning** [comment]
请问您部署开源的paas，可以部署s-mark应用嘛

**Comment by wklken** [comment]
最新版已加tooltips
