### ISSUE TITLE
./globals.env: line 36: HAS_DNS_SERVER: command not found

### ISSUE THREAD

**Issue by wiljay** [Tencent/bk-PaaS#138]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

bug
**PaaS/PaaSAgent版本(The versions used):**

5.0.4
**发生了什么(What happened):**
运行程序时出现./globals.env: line 36: HAS_DNS_SERVER: command not found

**期望是什么(What you expected to happen):**

如何解决
**如何复现(How to reproduce it):**

在install 下运行./bkcec start redis 或mysql时
**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
![image](https://user-images.githubusercontent.com/42308868/59732979-dd6db580-927e-11e9-938f-81e092aa5d89.png)

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
请到 https://bk.tencent.com/s-mart/community/ 论坛发帖, 会得到相关的支持和协助;

bk-PaaS 只维护蓝鲸智云PaaS开源版相关的bug及feature;  社区版及企业版的issues请到论坛发帖; Close;
