### ISSUE TITLE
希望提供自定义 supervisor 启动的进程的能力

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-PaaS#151]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

需求提交

**PaaS/PaaSAgent版本(The versions used):**

`V3.2.2`

**发生了什么(What happened):**

目前 S-mart 应用部署时无法自定义 supervisor 启动的进程 

**期望是什么(What you expected to happen):**

希望开放自定义 supervisor 启动的进程的能力

**Comment by wklken** [comment]
- 目前使用的 supervisord 模板是: https://github.com/Tencent/bk-PaaS/blob/master/paas-ce/paasagent/etc/templates/supervisord.conf
- 而模板渲染的操作是在go代码中做的, 由于存在一系列系统于定义约定, 所以暂时逻辑都在代码中

- 可以根据需求自行修改

--------------

自定义 supervisor 启动进程, 是希望什么形式的? 能否具体描述下, 如果PaaS提供的这种能力, SaaS如何进行自定义?

**Comment by homholueng** [comment]
提出这个需求是因为以下原因：
- SaaS 希望启动监听不同队列且使用不同并发策略的 celery worker 来对 worker 进行更加精细的划分，所以希望能够自定义 celery worker 的启动命令

**目前看来可以先只满足自定义 celery worker 进程的启动命令，至于启动目录，日志文件等选项可以保持不变。**

自定义方式大致如下：

1. 在 SaaS 软件包中的 `app.yml` 文件中定义自定义 celery 的命令，例如：

```yml
celery workers:
  - {{python}} manage.py celery worker -Q pipeline -n pipeline_worker@%h -c 6 -l info --maxtasksperchild=50
  - celery worker -A blueapps.core.celery -P gevent -Q service_schedule -c 100 -l info -n schedule_worker@%h --maxtasksperchild=50
  - {{python}} manage.py celery worker -Q pipeline_additional_task -n common_worker@%h -c 6 -l info --maxtasksperchild=50
```

2. 在渲染 supervisord 模板时，根据是否有自定义 celery worker 启动命令来决定渲染策略：
- 无：走默认渲染策略
- 有：使用用户配置的命令渲染模板

**Comment by wklken** [comment]
- 这里的逻辑类似heroku buildpack的procfile, 一切启动命令可以由用户自行指定; 
- 当前基于virtualenv/docker的企业版社区版暂时不支持, 这个需求我们会评估下

**Comment by wklken** [comment]
企业版的paas_agent 2.5.11 已支持自定义启动命令

----------------------

社区版或开源版可以自行改造:
- 在源代码根路径下建立约定文件, 例如 support-files/supervisord.conf 
- 修改paas_agent部署的build shell脚本, 检测源代码目录, 存在的话优先使用源代码中的文件
