### ISSUE TITLE
PaaS控制面板用户管理链接404

### ISSUE THREAD

**Issue by chainingning** [Tencent/bk-PaaS#152]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG

**PaaS/PaaSAgent版本(The versions used):**
3.2.521

**发生了什么(What happened):**
在PaaS的应用面板中点击用户管理，出现404，应该是端口不对

**期望是什么(What you expected to happen):**
正常跳转到用户管理

**如何复现(How to reproduce it):**
开源PaaS部署好之后，首先访问http://www.bking.com:8001/platform/，然后在右侧的常用链接中点击用户管理。

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

[15/Aug/2019 10:03:16] "GET /login/accounts/user/list/ HTTP/1.1" 404 3915

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
最新社区版已处理
