### ISSUE TITLE
用户认证报错

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-PaaS#154]
在搭建好开源bk-paas后，又部署了标准化运维，现在访问标准化运维报错如下：
![image](https://user-images.githubusercontent.com/43264876/63821183-938c0480-c97e-11e9-9253-6247d6742ba3.png)
 查看标准化运维日志如下：
![image](https://user-images.githubusercontent.com/43264876/63821210-b4545a00-c97e-11e9-9968-d86ba9f3d62a.png)
查看esb日志如下：
![image](https://user-images.githubusercontent.com/43264876/63821240-cb934780-c97e-11e9-8251-20dd62e384e7.png)
查看login日志如下：
![image](https://user-images.githubusercontent.com/43264876/63821267-ee256080-c97e-11e9-858b-128cd38dd4cf.png)
发现 bk_username 经过esb传给login后内容没有了。
请问是esb是哪里配置不对吗？

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/blob/master/paas-ce/paas/login/bkaccount/views_api_v2.py#L33

![image](https://user-images.githubusercontent.com/2002216/63821783-dcdd5380-c980-11e9-98c4-b967d362e1db.png)


@alex-smile 看代码, 来自esb的请求是需要带`bk_username`的, 需要确认下逻辑

**Comment by alex-smile** [comment]
请求 bk_login get_user 组件，默认需提供参数用户登录态 bk_token，如果希望使用 bk_username，则需要先将 bk_app_code 添加到用户免认证白名单中

**Comment by makerwei** [comment]
@wklken @alex-smile 感谢回复，代码逻辑我看了，没有什么问题，白名单那个我试试，再次感谢
