### ISSUE TITLE
用户管理接口

### ISSUE THREAD

**Issue by mechine** [Tencent/bk-PaaS#162]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
FEATURE REQUEST

**PaaS/PaaSAgent版本(The versions used):**

**发生了什么(What happened):**
用户名存在无法创建用户-》 所以我选择更新用户-》更新用户需要用户ID
没有API接口可以获取包含用户ID的信息

**期望是什么(What you expected to happen):**
我希望能用接口创建用户，或者修改用户信息

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
API 网关 蓝鲸统一登录 BK_LOGIN 的接口`/api/c/compapi/v2/bk_login/get_user/`

可以通过用户名获取用户信息, 进而判断是否存在

**Comment by wklken** [comment]
具体的接口代码:
https://github.com/Tencent/bk-PaaS/blob/master/paas-ce/paas/login/bkaccount/views_api_v2.py

可以参考实现
