### ISSUE TITLE
paasagent编译时报错

### ISSUE THREAD

**Issue by tianqi0514** [Tencent/bk-PaaS#177]
系统：centos7.5
执行命令：
![image](https://user-images.githubusercontent.com/52562520/77737144-5852d080-7048-11ea-9939-0cc1a355d312.png)
执行报错：
![image](https://user-images.githubusercontent.com/52562520/77737172-69034680-7048-11ea-842b-b05ccb52e72b.png)

**Comment by tianqi0514** [comment]
按照官方文档中执行到make的时候报错，报的错如下：[root@localhost paasagent]# make
go build -o bin/paas_agent -v -i main.go
paasagent/vendor/golang.org/x/sys/unix
paasagent/vendor/github.com/fsnotify/fsnotify
paasagent/vendor/github.com/hashicorp/hcl/hcl/strconv
paasagent/vendor/github.com/hashicorp/hcl/hcl/token
paasagent/vendor/github.com/hashicorp/hcl/hcl/ast
paasagent/vendor/github.com/hashicorp/hcl/hcl/scanner
paasagent/vendor/github.com/hashicorp/hcl/hcl/parser
paasagent/vendor/github.com/hashicorp/hcl/json/token
paasagent/vendor/github.com/hashicorp/hcl/json/scanner
paasagent/vendor/github.com/hashicorp/hcl/json/parser
paasagent/vendor/github.com/hashicorp/hcl
paasagent/vendor/github.com/hashicorp/hcl/hcl/printer
paasagent/vendor/github.com/magiconair/properties
paasagent/vendor/github.com/mitchellh/mapstructure
paasagent/vendor/github.com/pelletier/go-toml
paasagent/vendor/github.com/spf13/afero/mem
paasagent/vendor/golang.org/x/text/transform
paasagent/vendor/golang.org/x/text/unicode/norm
paasagent/vendor/github.com/spf13/afero
paasagent/vendor/github.com/spf13/cast
paasagent/vendor/github.com/spf13/jwalterweatherman
paasagent/vendor/github.com/spf13/pflag
paasagent/vendor/gopkg.in/yaml.v2
paasagent/vendor/github.com/spf13/viper
paasagent/vendor/github.com/moul/http2curl
paasagent/vendor/github.com/pkg/errors
paasagent/vendor/golang.org/x/net/publicsuffix
paasagent/vendor/github.com/parnurzeal/gorequest
paasagent/core
# paasagent/core
core/utils.go:46:14: undefined: syscall.GetStdHandle
core/utils.go:47:33: undefined: syscall.PROCESS_TERMINATE
paasagent/vendor/github.com/labstack/echo/context
paasagent/vendor/github.com/mattn/go-colorable
paasagent/vendor/github.com/mattn/go-isatty
paasagent/vendor/github.com/labstack/gommon/color
paasagent/vendor/github.com/valyala/fasttemplate
paasagent/vendor/github.com/labstack/gommon/log
paasagent/vendor/github.com/labstack/echo/log
paasagent/vendor/github.com/labstack/echo/engine
paasagent/vendor/github.com/labstack/echo
paasagent/vendor/github.com/labstack/echo/engine/standard
make: *** [build] 错误 2

**Comment by wklken** [comment]
使用的go版本是?

PaaSAgent是基于go 1.11.2开发的, 可以用gvm安装后尝试编译

**Comment by tianqi0514** [comment]
我使用的是1.11.2，仍然会出现同样的报错





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午5:44
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] paasagent编译时报错 (#177)





 
使用的go版本是?
 
PaaSAgent是基于go 1.11.2开发的, 可以用gvm安装后尝试编译

**Comment by tianqi0514** [comment]
编译问题已解决，我 部署开源版的openpaas，缺少如图中所述的这个tar包，请问在哪里可以下载？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午5:44
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] paasagent编译时报错 (#177)





 
使用的go版本是?
 
PaaSAgent是基于go 1.11.2开发的, 可以用gvm安装后尝试编译

**Comment by wklken** [comment]
哪个tar包? 麻烦发下文件名

**Comment by tianqi0514** [comment]
extras_V*.tgz.gz




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午5:08
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] paasagent编译时报错 (#177)





 
哪个tar包? 麻烦发下文件名

**Comment by tianqi0514** [comment]
你好，因缺少上封右键中的tar包，现在在做社区版往开源版的迁移，迁移之后激活appo会报错，部署smart应用也会报错，mysql的配置我是和社区版用的一样的，配置是没有问题的，问了社区版的开发人员，说这个需要错需要询问openpaas的开发人员，请指导一下，谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"406031135"<406031135@qq.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上8:19
收件人:&nbsp;"Tencent/bk-PaaS"<reply@reply.github.com&gt;;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;回复： [Tencent/bk-PaaS] paasagent编译时报错 (#177)



extras_V*.tgz.gz




------------------ 原始邮件 ------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午5:08
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] paasagent编译时报错 (#177)





 
哪个tar包? 麻烦发下文件名

**Comment by wklken** [comment]
@tencent-adm 

![image](https://user-images.githubusercontent.com/2002216/78127648-21652c00-7447-11ea-9d2e-4f7de1502474.png)

`extras_V*.tar.gz` 这个是很久之前提供的RabbitMQ安装包; 开源版是不提供的

可以自行安装好`RabbitMQ`, 或者使用社区版部署脚本中MQ的安装脚本进行安装
