### ISSUE TITLE
部署smart应用失败

### ISSUE THREAD

**Issue by tianqi0514** [Tencent/bk-PaaS#178]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
最新的开源版本

**发生了什么(What happened):**
部署smart应用失败

**期望是什么(What you expected to happen):**
部署smart应用成功

**如何复现(How to reproduce it):**
部署任意一个smart应用时会出现

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
paas.log
![image](https://user-images.githubusercontent.com/52562520/78740897-8ca08800-798a-11ea-934f-a13ac59340a3.png)
paas_gunicorn.log
![image](https://user-images.githubusercontent.com/52562520/78740947-a4780c00-798a-11ea-9431-85857f47f2b8.png)
appengine_gunicorn.log
![image](https://user-images.githubusercontent.com/52562520/78740995-c5406180-798a-11ea-8014-67aa2c447e32.png)
agent.log
![image](https://user-images.githubusercontent.com/52562520/78741038-e3a65d00-798a-11ea-9f26-aec49b295570.png)

**备注(Anything else we need to know):** 
据我所知，部署smartapp成功的三个条件，paas的4大模块运行成功（nginx+gunicorn），正式服务器激活成功，rabbitmq激活成功，以上条件均已满足，rabbitmq是自行安装并且可以正常使用，版本也和社区版中的保持了一致

**Comment by wklken** [comment]
agent.log报错显示: 从对应地址下载tar.gz失败, 状态403

你可以到agent机器, 手动curl这个地址, 确认下为什么403; 是否加了网络策略限制? 

部署机制: paas发起部署, 最终agent执行, 此时, agent需要从paas下载用户上传的包到本机进行部署

**Comment by tianqi0514** [comment]
您好，非常感谢您的回复，我解决了这个问题。但是出现了另外一个问题，麻烦帮忙解答。
我的smart应用部署成功了，打开的时候报了504 timeout，nginx日志：

open-paas和paasagent的nginx的配置文件：
server {
&nbsp; &nbsp; listen&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 8085;
&nbsp; &nbsp; &nbsp; &nbsp; server_name&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;localhost;


&nbsp; &nbsp; client_max_body_size&nbsp; &nbsp; 512m;


&nbsp; &nbsp; &nbsp; &nbsp; location ~ ^/t/([^/]+)/static/(.*)$ {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; alias /home/paasagent/apps/projects/$1/code/$1/static/$2;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; location ~ ^/o/([^/]+)/static/(.*)$ {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; alias /home/paasagent/apps/projects/$1/code/$1/static/$2;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; location ~ ^/(t|o)/([^/]+) {
&nbsp; &nbsp; &nbsp; &nbsp; include uwsgi_params;


&nbsp; &nbsp; &nbsp; &nbsp; if (!-f /home/paasagent/apps/projects/$2/run/uwsgi.pid) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return 404;
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; uwsgi_pass&nbsp; unix:/home/paasagent/apps/projects/$2/run/uwsgi.sock;
&nbsp; &nbsp; &nbsp; &nbsp; uwsgi_param SCRIPT_NAME /$1/$2;
&nbsp; &nbsp; &nbsp; &nbsp; uwsgi_read_timeout 300;
&nbsp; &nbsp; &nbsp; &nbsp; uwsgi_modifier1 30;
&nbsp; &nbsp; }


}

----
upstream OPEN_PAAS {
&nbsp; &nbsp; server 127.0.0.1:8001 max_fails=1&nbsp; fail_timeout=30s;
}
upstream OPEN_PAAS_APPENGINE {
&nbsp; &nbsp; server 127.0.0.1:8000 max_fails=1&nbsp; fail_timeout=30s;
}
upstream OPEN_PAAS_ESB {
&nbsp; &nbsp; server 127.0.0.1:8002 max_fails=1&nbsp; fail_timeout=30s;
}
upstream OPEN_PAAS_LOGIN {
&nbsp; &nbsp; server 127.0.0.1:8003 max_fails=1&nbsp; fail_timeout=30s;
}


# upstream - paasagent
upstream PAAS_AGENT_TEST {
&nbsp; &nbsp; server 192.168.1.1:8085 max_fails=1&nbsp; fail_timeout=30s;
}
upstream PAAS_AGENT_PROD {
&nbsp; &nbsp; server 172.16.255.138:8085 max_fails=1&nbsp; fail_timeout=30s;
}
# proxy_next_upstream&nbsp; http_502 http_504 error timeout invalid_header;


server {
&nbsp; &nbsp; listen&nbsp; &nbsp; &nbsp; &nbsp;80;
&nbsp; &nbsp; server_name&nbsp; www.bking.com;


&nbsp; &nbsp; access_log /var/log/nginx/openpaas_osce_access.log;
&nbsp; &nbsp; error_log /var/log/nginx/openpaas_osce_error.log;


&nbsp; &nbsp; client_max_body_size&nbsp; &nbsp; 512m;


&nbsp; &nbsp; # ============================ paas ============================
&nbsp; &nbsp; # PAAS_SERVICE HOST/PORT
&nbsp; &nbsp; location / {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://OPEN_PAAS;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }


&nbsp; &nbsp; # PAAS_SERVICE HOST/PORT, for doc
&nbsp; &nbsp; location ~ ^/doc/(.*) {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://OPEN_PAAS/static/doc/$1$is_args$args;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;


&nbsp; &nbsp; }




&nbsp; &nbsp; # ============================ appengine ============================
&nbsp; &nbsp; # ENGINE_SERVICE HOST/PORT
&nbsp; &nbsp; location ~ ^/v1 {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://OPEN_PAAS_APPENGINE;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }


&nbsp; &nbsp; # ============================ esb ============================
&nbsp; &nbsp; # ESB_SERVICE HOST/PORT
&nbsp; &nbsp; location ~ ^/api/(.*) {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://OPEN_PAAS_ESB/$1$is_args$args;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Request-Uri $request_uri;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }




&nbsp; &nbsp; # ============================ login ============================
&nbsp; &nbsp; # LOGIN_SERVICE HOST/PORT
&nbsp; &nbsp; location ~ ^/login/(.*) {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://OPEN_PAAS_LOGIN/$1$is_args$args;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }




&nbsp; &nbsp; # ============================ paas_agent ============================
&nbsp; &nbsp; # for apps test
&nbsp; &nbsp; location ~ ^/t/ {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://PAAS_AGENT_TEST;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }


&nbsp; &nbsp; # for apps prod
&nbsp; &nbsp; location ~ ^/o/ {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://PAAS_AGENT_PROD;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass_header Server;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Scheme $scheme;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_read_timeout 600;
&nbsp; &nbsp; }


}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 下午3:50
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] 部署smart应用失败 (#178)





 
agent.log报错显示: 从对应地址下载tar.gz失败, 状态403
 
你可以到agent机器, 手动curl这个地址, 确认下为什么403; 是否加了网络策略限制?
 
部署机制: paas发起部署, 最终agent执行, 此时, agent需要从paas下载用户上传的包到本机进行部署

**Comment by wklken** [comment]
追一下请求, 确认下请求到哪个节点中断

前端请求 -> paas nginx(access log) -> paasagent nginx(access  log) -> 应用(uwsgi日志)

**Comment by tianqi0514** [comment]
您好，我的paas和paasagent是放在了同一台机器上，文件是用的您这边提供的示例文件，若是放在单机上进行部署，nginx配置文件是否需要修改？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wklken"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 晚上7:53
收件人:&nbsp;"Tencent/bk-PaaS"<bk-PaaS@noreply.github.com&gt;;
抄送:&nbsp;"田琪"<406031135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/bk-PaaS] 部署smart应用失败 (#178)





 
追一下请求, 确认下请求到哪个节点中断
 
前端请求 -&gt; paas nginx(access log) -&gt; paasagent nginx(access  log) -&gt; 应用(uwsgi日志)
