### ISSUE TITLE
不安全的哈希算法

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/bk-PaaS#180]
https://github.com/Tencent/bk-PaaS/blob/7a6fe1ef38a7e4e2bd11a6c2efa871a967ac2a3c/paas-ce/paas/paas/user_center/weixin/core.py#L173

在安全性要求较高的系统中，不应使用被业界公认的不安全的哈希算法（如MD5、SHA-1等)来保证数据的完整性。应采用散列值>=224比特的SHA系列算法（如SHA-224、SHA-256、SHA-384和SHA-512）来保证敏感数据的完整性。

**Comment by wklken** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Access_Overview.html#%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%9A%E9%AA%8C%E8%AF%81%E6%B6%88%E6%81%AF%E7%9A%84%E7%A1%AE%E6%9D%A5%E8%87%AA%E5%BE%AE%E4%BF%A1%E6%9C%8D%E5%8A%A1%E5%99%A8

这是微信官方回调协议, 用于验证请求是否来自于微信;
