### ISSUE TITLE
开源版paas部署部分saas后无限登录

### ISSUE THREAD

**Issue by tianqi0514github** [Tencent/bk-PaaS#182]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
开源版

**发生了什么(What happened):**
开源paas部署完成后，可以正常加载开发样例、开发框架以及smart应用市场下载的开源组件，但是其中带有社区版字眼的组件，只能将V4的部署成功，而且部署成功后，进入该saas时，会无限登录，而其他非社区版的saas则可以正常使用。

**期望是什么(What you expected to happen):**
希望开源版的paas可以成功加载故障治愈、日志检索、节点管理等在smart市场只包含社区版字眼的saas，例如这种：
![image](https://user-images.githubusercontent.com/53246865/79294483-dea45900-7f08-11ea-86ef-34ecf77187c6.png)

**如何复现(How to reproduce it):**
每次进入该saas时

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
bk_fta_solutions.log 以bk_fta_solutions为例
![image](https://user-images.githubusercontent.com/53246865/79294483-dea45900-7f08-11ea-86ef-34ecf77187c6.png)

**备注(Anything else we need to know):** 
若需使用开源版的paas，想问一下您这边是建议自己部署还是从社区版迁移，谢谢。

**Comment by wklken** [comment]
日志图重复了, 所以没法确认问题

------------
登录的逻辑:
1  登录页面 -> 2 登录成功 -> 3 在域下面写登录态cookie -> 4 跳转到saas -> 5 saas从域下读取登录态cookie  - > 6  saas拿bk_token, 调用登录服务, 校验登录态 -> 7 调用失败或者校验失败, saas又跳回登录页面

无限登录原因:
- 6 拿不到bk_token, 此时需要确认登录态写的域是否一致
- 7 调用登录接口失败(这个saas会打日志)
- 7 调用登录接口成功, 但是登录态非法(这个saas会打日志)

具体通过日志定位下


------------

开源版替换社区版我们有提供相关文档: https://bk.tencent.com/docs/document/5.1/20/630#osed

社区版有相关的运维工具, 开源版只有相关文档参考, 但是开源版相对更`透明`;  

对社区版熟悉的话建议迁移, 没有使用过社区版的话建议全新部署

**Comment by wklken** [comment]
登录对接逻辑 https://bk.tencent.com/docs/document/6.0/130/5925
如果有问题再重新开启
