### ISSUE TITLE
prop-tips

### ISSUE THREAD

**Issue by GONGONGONG** [Tencent/bk-PaaS#203]
去掉icon，label hover展示tips
![image](https://user-images.githubusercontent.com/29882448/82776901-09c28680-9e7f-11ea-87cc-1ba901fa0a27.png)

**Comment by GONGONGONG** [comment]
修改id处样式
![image](https://user-images.githubusercontent.com/29882448/82777339-6c685200-9e80-11ea-9e5e-768c7bff5ab3.png)

**Comment by ielgnaw** [comment]
done
