### ISSUE TITLE
【lesscode需求】组件如何联动

### ISSUE THREAD

**Issue by chenhongen** [Tencent/bk-PaaS#239]
**需求提交** 

**PaaS/PaaSAgent版本(The versions used):**
latest

**发生了什么(What happened):**
组件如何联动

**期望是什么(What you expected to happen):**
比如点击“按钮”清空“输入框”内容如何通过可视化编辑器实现，是否有类似demo可以展示。

**Comment by ielgnaw** [comment]
组件之间的联动这个需求我们正在开发中，不仅仅是点击按钮清空输入框这种需求，还包括下拉框之间的联动、点击按钮触发 ajax 异步加载数据然后渲染表格等等类似的场景。

敬请期待~

**Comment by chenhongen** [comment]
是的，计划大概什么时候会发布一版呢

**Comment by ielgnaw** [comment]
这个预计是八月份

**Comment by chenhongen** [comment]
时间有点久。。如果我们想自己实现的话有什么思路可以提供吗？在不通过操作ref的情况下。

**Comment by ielgnaw** [comment]
目前只能下载 vue 源码后，自己修改代码来实现。我们对二次开发是很友好的，生成的源码都比较工整，下载下来直接开发是很好上手的。

**Comment by sundytt** [comment]
lesscode-develop 分支已更新包含该功能
