### ISSUE TITLE
【lesscode】包含slots属性组件问题

### ISSUE THREAD

**Issue by chenhongen** [Tencent/bk-PaaS#282]
**BUG反馈:**

**PaaS/PaaSAgent版本(The versions used):**
lesscode 0.0.4

**发生了什么(What happened):**
拖拽2个单选组件（比如单选A和单选B）后，编辑其中一个单选A后，删除另一个单选B。此时单选组件全部被删除且伴随浏览器后端异常。

**如何复现(How to reproduce it):**
[复现截图](https://s1.ax1x.com/2020/09/04/wAJa9I.gif)

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

`vue.esm.js:647 [Vue warn]: Unknown custom element: <radio> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <RenderComponent> at lib/client/src/components/render/component.vue
       <Draggable>
         <RenderCol> at lib/client/src/components/render/col.vue
           <RenderRow> at lib/client/src/components/render/row.vue
             <RenderGrid> at lib/client/src/components/render/grid.vue
               <Draggable>
                 <Index> at lib/client/src/views/index/index.vue
                   <Index> at lib/client/src/views/index.vue
                     <App> at lib/client/src/App.vue
                       <Root>`

**备注(Anything else we need to know):** 
props包含slots的组件都有类似问题，如多选组件

**Comment by chenhongen** [comment]
目前我是这么处理的：
```
handleChange (key, payload) {
    const renderProps = { ...this.renderProps }
    if (key === 'slots') {
        renderProps.slots.val = payload.val
    } else {
        renderProps.slots = payload
    }
                
    this.renderProps = renderProps

    this.$emit('on-change', {
        renderProps
    })
}
```

**Comment by ielgnaw** [comment]
你好，感谢反馈

我们正在开发新的版本，在这个版本里，加入了很多功能，这个问题也已经修复了。敬请期待我们的新版本哈~

![Untitled](https://user-images.githubusercontent.com/1153430/93667023-50369380-fab5-11ea-9f0a-eac54e8d20bc.gif)

**Comment by ielgnaw** [comment]
对了 #239 这个里面的需求，在新版本里我们也解决了

**Comment by chenhongen** [comment]
预计什么发新版[星星眼]

**Comment by chenhongen** [comment]
三个月过去了，还有希望吗。。

**Comment by ielgnaw** [comment]
LessCode新版本在内部推广试用中，开源版更新略滞后，烦请关注github后续更新，敬请谅解。

**Comment by sundytt** [comment]
@chenhongen  lesscode-develop分支已更新为最新版本
