### ISSUE TITLE
【lesscode】数据源切回array类型失败

### ISSUE THREAD

**Issue by Lukol** [Tencent/bk-PaaS#346]
![image](https://user-images.githubusercontent.com/23112406/119630134-3bc74980-be41-11eb-9fb3-919ce5c2b222.png)
数据源类型切成remote之后，再切回array需编辑数据才生效，否则仍是remote类型。

**Comment by sundytt** [comment]
画布中当前组件属性切换Tab，保存所有Tab对应的当前编辑值，切换组件或保存画布时，保存该组件属性最终选择的Tab及对应值

**Comment by sundytt** [comment]
done
