### ISSUE TITLE
【lesscode】每个组件里，数据源可绑定远程数据的，给出数据示例

### ISSUE THREAD

**Issue by sundytt** [Tencent/bk-PaaS#433]
![image](https://user-images.githubusercontent.com/30256396/126430902-e3b8f393-6e1b-46b6-9a12-918a05bd1d93.png)

**Comment by Lukol** [comment]
需测试的组件：
蓝鲸组件库：
- [ ] 表单容器
- [ ] 单选框
- [ ] 多选框
- [ ] 按钮组
- [ ] 下拉选框
- [ ] 标签输入
- [ ] 查询选择
- [ ] 穿梭框
- [ ] 级联选框
- [ ] 选项卡
- [ ] 步骤
- [ ] 面包屑
- [ ] 时间轴
- [ ] 差异对比
- [ ] 轮播图
- [ ] 树（需讨论）：树组件的静态数据无论怎么改都会出现parent属性，使得数组里面存在循环引用，无法使用JSON.stringfy转化成字符串。
- [ ] 表格
- [ ] 大树
- [ ] echarts
- [ ] bkcharts
- [ ] 复合组件

element组件库：
- [ ] 单选框
- [ ] 多选框
- [ ] 下拉选框
- [ ] 级联选框
- [ ] 穿梭框
- [ ] 表格
- [ ] 树
- [ ] 选项卡
- [ ] 步骤
- [ ] 面包屑
- [ ] 走马灯
- [ ] 时间轴

**Comment by sundytt** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/30256396/130385006-81620a8b-5a99-4479-b62f-81fce3c19d2b.png)
