### ISSUE TITLE
【lesscode】表单组件 加上v-model 可以获取表单值

### ISSUE THREAD

**Issue by sundytt** [Tencent/bk-PaaS#436]
* [x]  标签输入
* [ ]  人员选择
* [ ]  穿梭框，获取选择后的列表
* [ ]  rate

**Comment by sundytt** [comment]
rate组件  预览时选择值无效

**Comment by Lukol** [comment]
- 标签输入：v-model
- 人员选择：开源版无该组件
- 穿梭框：v-bind:target-list
- rate：v-bind:rate

**Comment by Lukol** [comment]
穿梭框、rate组件无v-model属性

**Comment by Lukol** [comment]
rate组件问题：组件的rate属性必须含有sync修饰符才可以实现即时修改。
https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/rate?anchor=shu-xing
rate属性增加sync修饰符后，当rate值类型为变量时，可以在预览状态下实现即时修改。此时源码为：
![image](https://user-images.githubusercontent.com/23112406/127620788-226c7d78-ca83-41de-8e03-88493750a485.png)
当rate值类型为值时，源码缺少sync修饰符，无法即时修改。源码为：
![image](https://user-images.githubusercontent.com/23112406/127621094-866e062f-c7b8-4559-b6ea-ec70b210c8ed.png)
