### ISSUE TITLE
paas开发环境部署 No module named app_log

### ISSUE THREAD

**Issue by snailq** [Tencent/bk-PaaS#451]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
->BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
-> bk-PaaS-2.12.23

**发生了什么(What happened):**
部署web项目  paas时候
执行 python manage.py migrate 
ImportError: No module named app_log
app_log这个模块应该不是pip提供的    是在什么位置上呢？需要怎么安装呢？

**Comment by snailq** [comment]
发下是conf/default.py 里定义的，这几个模块是在哪里的呢？
    INSTALLED_APPS += (
        #"app_log",
        #"app_monitor",
        #"storage",
        #"esb.apps.status",
    )

另外发现login和paas的数据库表有冲突呢？
django.db.utils.InternalError: (1050, u"Table 'paas_app' already exists")

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/blob/2.12.23/paas2/paas/conf/default.py#L32

社区版及开源版需要 配置环境变量: `BK_PAAS_EDITION="ce"`

-----

目前2.12.x/2.13.x的版本统一了原开源版/社区版及企业版代码, 部署相关文档未更新, 合入master前会一并处理
