### ISSUE TITLE
【lesscode共建】请求不到蓝鲸统一登录接口

### ISSUE THREAD

**Issue by honger502** [Tencent/bk-PaaS#462]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**PaaS/PaaSAgent版本(The versions used):**
PaaS      3.2.5

**发生了什么(What happened):**
想要参与 lesscode 共建，本地启动了 PaaS 下的 appengine、paas、esb、login 四个web服务, 端口分别为 8000-8003。
也启动了 lesscode 服务，端口为 5000，配置好了 /etc/hosts 如 127.0.0.1 www.bking.com
访问 www.bking.com:5000 成功跳转到登录页，返回之后系统请求 api/c/compapi/v2/bk_login/get_user/  404

**期望是什么(What you expected to happen):**
此接口不在这四个web服务中，可以开放 api/c/compapi/v2/bk_login/get_user/ 此接口吗？

**备注(Anything else we need to know):** 
不希望部署套餐版，因为没有机器，仅本地开发。

**Comment by ielgnaw** [comment]
https://github.com/Tencent/bk-PaaS/blob/lesscode-develop/paas-ce/lesscode/lib/server/middleware/auth.js#L58 这个接口的 `hostUrl`，来自你的 `lesscode/lib/server/conf/http.js` 里的配置 https://github.com/Tencent/bk-PaaS/blob/lesscode-develop/paas-ce/lesscode/lib/server/middleware/auth.js#L30。

这个 `conf/http.js` 里的 `hostUrl` 配置应该是你 PaaS 的 login 服务的 url，你看看你的配置是否正确？

**Comment by honger502** [comment]
login 服务无此接口

**Comment by ielgnaw** [comment]
> 本地启动了 PaaS 下的 appengine、paas、esb、login 四个web服务, 端口分别为 8000-8003

就是这个 login 服务的接口
