### ISSUE TITLE
关于使用paas平台的想法

### ISSUE THREAD

**Issue by GJDevil** [Tencent/bk-PaaS#48]
关于paas开发使用技术的技术资料希望可以分享，提高我们对paas的熟悉时间。
建议增加项目总略图， 针对项目或者模块进行摘要，便于用户熟悉和开发扩展。

**Comment by zhangdavids** [comment]
点赞

**Comment by wklken** [comment]
感谢反馈, 我们还在梳理细化相关的文档

----

主体项目是基于Django1.8的(class-based-view/middleware/mixin/form/ORM等), 所以需要有python/Django基础; 如果对Django有疑问, 可以参考 [Django官方文档](https://docs.djangoproject.com/en/1.8/)

----

目前已有的文档, 建议阅读顺序

1.  [蓝鲸PAAS平台白皮书](https://docs.bk.tencent.com/paas/), 对PaaS产品有一个整体的了解, 包括功能及模块组成等
2. github项目的README.md以及每个子项目的README.md
3. 大部分代码都包含注释, django项目建议从urls.py入口, 按图索骥可以进入到各个功能的具体逻辑

**Comment by baiyunchen** [comment]
基于容器技术的应用部署这部分社区版砍掉了实在是可惜，我感觉现在的这类平台docker支持是必备功能~

**Comment by spearsharp** [comment]
有没有paas平台本地pycharm配置本地运行的文档，可以参考，我正在配置一个bk_pass但是直接连的github上tecent 里的git，好想在自己电脑上跑起来看看

**Comment by wklken** [comment]
@spearsharp 建议使用容器话版本快速体验 https://github.com/Tencent/bk-PaaS/issues/83
本地搭建可以参考README.md中安装文档
