### ISSUE TITLE
【Lesscode】需求-表单容器支持一次添加多个form-item

### ISSUE THREAD

**Issue by xintaoLi** [Tencent/bk-PaaS#513]
表单容器组件：
![image](https://user-images.githubusercontent.com/9812285/131624407-f079585d-9580-4506-8d38-cfd2c1161716.png)

一般使用时很少会只用到一个表单组件，这里的配置项只能一个一个添加，期望可以一次添加多个form-item，配置完毕一次提交保存

**Comment by LAnTime** [comment]
按钮修改为：提交并继续
