### ISSUE TITLE
【Lesscode】（需求）- 期望可以支持拖拽的组件组合可以保存为模板（当前项目的业务组件）

### ISSUE THREAD

**Issue by xintaoLi** [Tencent/bk-PaaS#515]
![image](https://user-images.githubusercontent.com/9812285/131625908-17232a2b-898c-442a-8804-e5fb2ead2874.png)

例如上面这个搜索面板，在这个项目中很多页面都有用到，期望可以右键选中这个组合，另存为模板或者组件，在其他页面或者本页面可复用

**Comment by sundytt** [comment]
模板功能在自测中啦
