### ISSUE TITLE
【lesscode】补充官网类的横向导航自定义组件

### ISSUE THREAD

**Issue by sundytt** [Tencent/bk-PaaS#516]
- [ ] ![image](https://user-images.githubusercontent.com/30256396/131634805-5ecf789c-5ee2-4644-bbc1-c63b0cf4ed10.png)

**Comment by terlinhe** [comment]
加上footer

**Comment by terlinhe** [comment]
处理好用户信息和退出

**Comment by sundytt** [comment]
通过模板配置
