### ISSUE TITLE
【lesscode】体验问题

### ISSUE THREAD

**Issue by Lukol** [Tencent/bk-PaaS#631]

**Comment by zmlplus** [comment]
画布编辑页，右侧配置栏收回后页面闪动

**Comment by zmlplus** [comment]
画布编辑页，左侧菜单收回后，菜单的提示红点还在
![企业微信截图_16364486632011](https://user-images.githubusercontent.com/56629728/140910775-4fc6ec06-ee16-438d-aaf1-c0165bbc0ab0.png)
![企业微信截图_16364486507763](https://user-images.githubusercontent.com/56629728/140910758-465c52b8-0e83-4e63-95aa-fab682974e8f.png)

**Comment by zmlplus** [comment]
组件v-model绑定“值”后，预览页面空白并报警告
![企业微信截图_16364551216222](https://user-images.githubusercontent.com/56629728/140911183-cc4c72dd-f027-4731-bdea-297001e6c95d.png)
![企业微信截图_16364551893216](https://user-images.githubusercontent.com/56629728/140911353-88238490-1c2a-40cf-8027-482273cbc87b.png)

**Comment by Lukol** [comment]
- [ ] 快捷键说明展示不全 
![image](https://user-images.githubusercontent.com/23112406/141097788-99c7612b-4b04-42a4-b7f9-1e1ba7d173ca.png)

**Comment by zmlplus** [comment]
蓝鲸Vue组件库 -> 表单 -> 滑动选择，层级问题，可在画布中滑动
![企业微信截图_163653300897](https://user-images.githubusercontent.com/56629728/141077726-18e81748-f64a-46bd-ad3b-fef15699b557.png)

**Comment by zmlplus** [comment]
栅格布局中的组件可以拖拽进自由布局中，自由布局中的组件无法拖拽进栅格布局中

**Comment by zmlplus** [comment]
属性配置中，颜色选择器被遮挡
![企业微信截图_16370414657557](https://user-images.githubusercontent.com/56629728/141927994-91dab32f-4443-4a09-8263-94ff09fb6694.png)

**Comment by zmlplus** [comment]
属性配置中，颜色选择无背景色，当组件再次获得焦点时，背景色变成默认值
![企业微信截图_16370414262765](https://user-images.githubusercontent.com/56629728/141928266-f3a81d36-8a0c-4894-a462-b1161b28d313.png)
![企业微信截图_16370414392046](https://user-images.githubusercontent.com/56629728/141928271-56dcd30e-5ca7-4c6f-a070-9e9c1905440d.png)
