### ISSUE TITLE
【lesscode】自定义组件

### ISSUE THREAD

**Issue by Lukol** [Tencent/bk-PaaS#635]
- [x] 快捷入口
![image](https://user-images.githubusercontent.com/23112406/140925929-42bba0fb-403a-480c-8ed7-1025d6b9241a.png)

- [x] 卡片
![image](https://user-images.githubusercontent.com/23112406/140925975-bc09d9be-8b71-4cc6-b207-dfc67c83d325.png)

- [x] 代码编辑器
![image](https://user-images.githubusercontent.com/23112406/140926052-d7fa0240-f23e-4dd0-8521-c82b63f2e02b.png)

- [x] markdown
![image](https://user-images.githubusercontent.com/23112406/140926116-0c687031-8153-4680-98aa-aa02e8863cf6.png)

- [x] 终端
![image](https://user-images.githubusercontent.com/23112406/140926184-c7eb52fa-2e66-497a-ac61-10f4a8b192f0.png)
- [x] 富文本编辑器
![image](https://user-images.githubusercontent.com/23112406/140926148-c14b7321-5d3c-4383-96ba-5be8e98890c5.png)

**Comment by ielgnaw** [comment]
快捷入口和卡片两个组件做成复合组件

其他的几个组件先 check 一下开源协议，可用的话做成 npm 模块。
