### ISSUE TITLE
develop分支的代码，用python3似乎运行不起来？

### ISSUE THREAD

**Issue by YDHui** [Tencent/bk-PaaS#689]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
3.2.5

**发生了什么(What happened):**
clone了develop分支的代码进行本地开发，看上去是支持py3了，但是似乎还处于开发阶段？没法直接跑起来，鉴权和登录模块都重写了？

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
develop分支还是python2才能run的

ft_upgrade_py3 这个分支才是python3的, 测试中, 测试结束后会合并到develop
