### ISSUE TITLE
PaaS部署成功，但是访问部到静态资源

### ISSUE THREAD

**Issue by jiaohongtao** [Tencent/bk-PaaS#712]
**PaaS版本(The versions used):**
3.2.5

**发生了什么(What happened):**
部署生产环境访问不到资源

**期望是什么(What you expected to happen):**
部署生产环境访问到资源

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

![image](https://user-images.githubusercontent.com/44717089/153141445-e83804f7-e242-493b-b931-31905d37d90e.png)
相关配置
![image](https://user-images.githubusercontent.com/44717089/153141585-21d5ec4f-20ea-4ce9-860b-7afa5d65e906.png)

**Comment by wklken** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/2002216/153351344-de5ac592-8130-4a1c-ada9-61e5027ab3dd.png">

本地开发环境, login服务本身的地址是 `http://xxx.com/`; 访问静态资源的地址是: `/static/`

生产环境, 由于多个站点共用域名, login服务本身的地址是 `http://xxx.com/login/`; 访问静态资源地址是: `/login/static/` 

生产环境, SITE_URL 是`/`, 并配置相关nginx反向代理静态资源文件

-------

https://github.com/Tencent/bk-PaaS/blob/master/docs/install/ce_paas_install.md#%E9%83%A8%E7%BD%B2%E5%88%B0%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2002216/153351691-8a5bcbd6-f44b-4668-9773-f20d7dea6b80.png">


https://github.com/Tencent/bk-PaaS/blob/master/paas-ce/paas/examples/nginx_paas.conf#L89

**Comment by jiaohongtao** [comment]
> <img alt="image" width="803" src="https://user-images.githubusercontent.com/2002216/153351344-de5ac592-8130-4a1c-ada9-61e5027ab3dd.png">
> 
> 本地开发环境, login服务本身的地址是 `http://xxx.com/`; 访问静态资源的地址是: `/static/`
> 
> 生产环境, 由于多个站点共用域名, login服务本身的地址是 `http://xxx.com/login/`; 访问静态资源地址是: `/login/static/`
> 
> 生产环境, SITE_URL 是`/`, 并配置相关nginx反向代理静态资源文件
> 
> https://github.com/Tencent/bk-PaaS/blob/master/docs/install/ce_paas_install.md#%E9%83%A8%E7%BD%B2%E5%88%B0%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83
> 
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/2002216/153351691-8a5bcbd6-f44b-4668-9773-f20d7dea6b80.png">
> 
> https://github.com/Tencent/bk-PaaS/blob/master/paas-ce/paas/examples/nginx_paas.conf#L89

说的不对应呢，是 / ，还是 /login/
![image](https://user-images.githubusercontent.com/44717089/153355620-375694fa-92a0-4067-82db-4045fc6a3d42.png)

为什么配置的

**Comment by wklken** [comment]
生产是`/login/`

1. 没有缓存
2. 有时候可以有时候不行, 需要排查下是否部署了两台服务, 配置只改生效一台?

**Comment by jiaohongtao** [comment]
> 生产是`/login/`
> 
> 1. 没有缓存
> 2. 有时候可以有时候不行, 需要排查下是否部署了两台服务, 配置只改生效一台?

-------------
现在是在一台机器上部署的,
发现开发环境是可以访问就是注销有问题，生产环境只是静态资源加载部到404
![截图_16444789511331](https://user-images.githubusercontent.com/44717089/153360501-9ee371e3-021f-48c5-80da-891c919a029f.png)
![截图_16444789841923](https://user-images.githubusercontent.com/44717089/153360561-84657afb-19af-47fb-b899-2159157767fc.png)

**Comment by wklken** [comment]
1. 先不管开发环境, 关注生产环境
2. 给到生产环境目前的 nginx配置 / settings配置 / 启动命令

本质上, 是将 /login/static/ 流量转到 login服务 找不到本地的文件

**Comment by jiaohongtao** [comment]
> 1. 先不管开发环境, 关注生产环境
> 2. 给到生产环境目前的 nginx配置 / settings配置 / 启动命令
> 
> 本质上, 是将 /login/static/ 流量转到 login服务 找不到本地的文件

-----
启动命令
![image](https://user-images.githubusercontent.com/44717089/153367293-c06f4800-f003-4e5d-968c-75821a05b944.png)
settings配置
[LOGIN_settings_production.txt](https://github.com/Tencent/bk-PaaS/files/8039345/LOGIN_settings_production.txt)
启动命令
[nginx_paas_new.txt](https://github.com/Tencent/bk-PaaS/files/8039346/nginx_paas_new.txt)

**Comment by wklken** [comment]
试试:

```
cd login
python manage.py runserver 8003
```

感觉是启动命令所在的目录路径下找不到 `/static/`, 进入对应目录启动

**Comment by jiaohongtao** [comment]
> 试试:
> 
> ```
> cd login
> python manage.py runserver 8003
> ```
> 
> 感觉是启动命令所在的目录路径下找不到 `/static/`, 进入对应目录启动

----
啊啊啊！！！就是这个原因，我说咋一会儿能访问一会儿不能访问，谢谢啦
