### ISSUE TITLE
安装S-mart市场用户管理应用失败

### ISSUE THREAD

**Issue by xujiaja** [Tencent/bk-PaaS#720]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
master分支

**发生了什么(What happened):**
部署开源paas服务后，安装S-mart市场里面的用户管理应用，报错
![image](https://user-images.githubusercontent.com/23472286/154007348-d886830a-df10-4cc2-b3e7-4399c6748e3c.png)

**期望是什么(What you expected to happen):**
正常安装saas应用

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
是smart应用? 版本号等发一下

-----
应该是安装包不符合smart的规范(目录结构), 导致部署解压处理报错
