### ISSUE TITLE
移动端组件集成

### ISSUE THREAD

**Issue by forrany** [Tencent/bk-PaaS#774]
## 可集成组件

- [x] Button
- [x] Cell + CellGroup   (需要icon)
- [x] Icon
- [x] Image

- [x] Checkbox
- [x] DatetimePicker
- [x] Field  (需要icon)
- [x] NumberKeyborad(需要icon)
- [x] PasswordInput(需要icon)
- [x] Picker(需要icon)
- [x] Radio
- [x] Rate
- [x] Search(需要icon)
- [x] Slider
- [x] Step(需要icon)
- [x] Swtich
- [ ] Uploader

- [x] Loading(需要icon)

- [x] Badge
- [x] Circle(需要icon)
- [x] CountDown(需要icon)
- [x] Divider(需要icon)
- [x] Empty(需要icon)
- [x] NoticeBar(需要icon)
- [x] Progress
- [x] Skeleton(需要icon)
- [x] Steps
- [x] Tag(需要icon)

- [ ] ~~IndexBar(需要icon)~~

- [x] NavBar(需要icon)

- [x] Pagination

- [x] TreeSelect(需要icon)

**Comment by forrany** [comment]
BUG修复


 - 小屏
	- [] 画布小屏无法展示完全
	- [] 头部预览按钮重叠

- 源码切换到画布，预览不见了
- 段落在PC中单位为rem

**Comment by Lukol** [comment]
已集成的组件：
 Icon

 Image

 Checkbox

 DatetimePicker

 Field (需要icon)

 NumberKeyborad(需要icon)

 PasswordInput(需要icon)

 Picker(需要icon)

 Radio

 Rate
