### ISSUE TITLE
能否提供一个快速体验的docker版本？

### ISSUE THREAD

**Issue by doterme** [Tencent/bk-PaaS#83]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**PaaS/PaaSAgent版本(The versions used):**

**发生了什么(What happened):**

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
我们有相应的计划, 还在验证中:)

**Comment by doterme** [comment]
@wklken 期待

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/blob/master/docs/wiki/container-support.md

已提供第一版, 用于体验; 第二版还在处理, 优化支持paasagent部署
