### ISSUE TITLE
S-mart 应用管理优化

### ISSUE THREAD

**Issue by sundytt** [Tencent/bk-PaaS#86]
1、S-mart应用列表，进入应用二级信息页面 增加返回操作
2、S-mart应用增加环境变量管理功能
3、UI优化：对齐
![image](https://user-images.githubusercontent.com/30256396/56412397-86ffed00-62b6-11e9-8914-841114a04c51.png)

**Comment by wklken** [comment]
duplicated to
https://github.com/Tencent/bk-PaaS/issues/101
https://github.com/Tencent/bk-PaaS/issues/100

close
