### ISSUE TITLE
安装过程中 pip install -r requirements.txt报错 error: cast between incompatible function types

### ISSUE THREAD

**Issue by boystray** [Tencent/bk-PaaS#91]
这是个bug报告，在安装paas过程中，执行 pip install -r requirements.txt命令，在uWSGI步骤报错：

  *** uWSGI compiling server core ***
  [thread 1][x86_64-linux-gnu-gcc -pthread] core/utils.o
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/protocol.o
  [thread 3][x86_64-linux-gnu-gcc -pthread] core/socket.o
  [thread 0][x86_64-linux-gnu-gcc -pthread] core/logging.o
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/master.o
  [thread 0][x86_64-linux-gnu-gcc -pthread] core/master_utils.o
  [thread 3][x86_64-linux-gnu-gcc -pthread] core/emperor.o
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/notify.o
  core/emperor.c: In function ‘uwsgi_emperor_vassal_start’:
  core/emperor.c:991:15: error: cast between incompatible function types from ‘void (*)(struct uwsgi_instance *)’ to ‘int (*)(void *)’ [-Werror=cast-function-type]
     pid = clone((int (*)(void *)) uwsgi_emperor_spawn_vassal, stack + PTHREAD_STACK_MIN, SIGCHLD | uwsgi.emperor_clone, (void *) n_ui);
                 ^
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/mule.o
  [thread 0][x86_64-linux-gnu-gcc -pthread] core/subscription.o
  [thread 1][x86_64-linux-gnu-gcc -pthread] core/stats.o
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/sendfile.o
  [thread 2][x86_64-linux-gnu-gcc -pthread] core/async.o
  cc1: all warnings being treated as errors

  ----------------------------------------
  Failed building wheel for uWSGI
  Running setup.py clean for uWSGI
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /home/hatech/.cache/pip/wheels/ad/56/bc/1522f864feb2a358ea6f1a92b4798d69ac783a28e80567a18b
  Running setup.py bdist_wheel for django-bootstrap-form ... done
  Stored in directory: /home/hatech/.cache/pip/wheels/28/98/3b/25275ae47e7c779faeb0e6326d7873b0f72cb5e5b743b4b573
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /home/hatech/.cache/pip/wheels/d5/0a/9e/cf4ae0888c3bc8b3739fd54b37893f47418f680c20ec7b0485
  Running setup.py bdist_wheel for static3 ... done
  Stored in directory: /home/hatech/.cache/pip/wheels/c3/d0/4b/a415104b0303aa18d566463b02d1eacb8f43bc3d29a6dc4574
Successfully built dj-static mako pycrypto PyYAML django-bootstrap-form Markdown static3
Failed to build uWSGI
Installing collected packages: django, static3, dj-static, MarkupSafe, mako, pycrypto, chardet, idna, certifi, urllib3, requests, gunicorn, uWSGI, elasticsearch, pymysql, redis, PyYAML, Pillow, greenlet, gevent, pytz, enum34, jinja2, django-bootstrap-form, Markdown, pygments, funcsigs, pbr, six, mock
  Running setup.py install for uWSGI ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GjrCw4/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XGAOP_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/8/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    detected CPU cores: 4
    configured CFLAGS: -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY -DUWSGI_VERSION="\"2.0.13.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="13" -DUWSGI_VERSION_REVISION="1" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -DUWSGI_XML -DUWSGI_XML_EXPAT -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
    *** uWSGI compiling server core ***
    core/utils.o is up to date
    core/protocol.o is up to date
    core/socket.o is up to date
    core/logging.o is up to date
    core/master.o is up to date
    core/master_utils.o is up to date
    [thread 1][x86_64-linux-gnu-gcc -pthread] core/emperor.o
    core/notify.o is up to date
    core/mule.o is up to date
    core/subscription.o is up to date
    core/stats.o is up to date
    core/sendfile.o is up to date
    core/async.o is up to date
    [thread 2][x86_64-linux-gnu-gcc -pthread] core/master_checks.o
    [thread 3][x86_64-linux-gnu-gcc -pthread] core/fifo.o
    [thread 0][x86_64-linux-gnu-gcc -pthread] core/offload.o
    core/emperor.c: In function ‘uwsgi_emperor_vassal_start’:
    core/emperor.c:991:15: error: cast between incompatible function types from ‘void (*)(struct uwsgi_instance *)’ to ‘int (*)(void *)’ [-Werror=cast-function-type]
       pid = clone((int (*)(void *)) uwsgi_emperor_spawn_vassal, stack + PTHREAD_STACK_MIN, SIGCHLD | uwsgi.emperor_clone, (void *) n_ui);
                   ^
    cc1: all warnings being treated as errors
    [thread 2][x86_64-linux-gnu-gcc -pthread] core/io.o

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GjrCw4/uWSGI/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XGAOP_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-GjrCw4/uWSGI/

**Comment by wklken** [comment]
- 开源版可以选择gunicorn启动(官方推荐), 此时可以不安装uwsgi, 可以将其从requirements.txt中去掉
- uwsgi安装时需要进行编译, 日志提示是编译错误, 跟用户本身的编译环境有关系, 可以google错误信息或者从uwsgi官方地址需求解决方案 [uwsgi issues](https://github.com/unbit/uwsgi/issues)

**Comment by boystray** [comment]
谢谢。

**Comment by mission802** [comment]
可以把 uWSGI 升级到 2.0.15 之后的版本，当前版本是 2.0.18
