### ISSUE TITLE
设置环境变量后启动仍是development server

### ISSUE THREAD

**Issue by yangbojun** [Tencent/bk-PaaS#92]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**PaaS/PaaSAgent版本(The versions used):**

**发生了什么(What happened):**

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by yangbojun** [comment]
版本：蓝鲸智云 PaaS 社区版3.2.2
使用的开源版部署，第一次部署拉起服务后访问不到http://www.bking.com:8001，服务器后端无请求显示，在服务器上使用curl -XGET "http://127.0.0.1:8001"可以看到请求并返回302
![image](https://user-images.githubusercontent.com/49931460/56630384-ceee8d80-6683-11e9-8707-362b9ff7035d.png)
于是尝试改为部署生产环境使用nginx代理，设置了环境变量BK_ENV="production"，但是拉起服务显示还是development server
![image](https://user-images.githubusercontent.com/49931460/56630519-3b698c80-6684-11e9-9eaf-5d70120eff86.png)
请问这种情况该怎么排查解决呢

**Comment by wklken** [comment]
- 这一行`Starting development server`是django打的, 只要是使用`python manage.py runserver`拉起的都会是`Starting development server`
- 要确认生效, 可以在`conf/settings_production.py`中加入打印语句, 生效将会加载`conf/settings_production.py`

**Comment by yangbojun** [comment]
> * 这一行`Starting development server`是django打的, 只要是使用`python manage.py runserver`拉起的都会是`Starting development server`
> * 要确认生效, 可以在`conf/settings_production.py`中加入打印语句, 生效将会加载`conf/settings_production.py`

好的，非常感谢已经可以正常访问了
