### ISSUE TITLE
我的应用-应用部署-下架 title错误

### ISSUE THREAD

**Issue by wklken** [Tencent/bk-PaaS#94]
页面位置: 我的应用 - 具体应用 - 应用部署 - 下架

问题描述: tilte错误, 应该是下架

截图:

![image](https://user-images.githubusercontent.com/2002216/56646771-d0837a00-66b2-11e9-8737-690a0b84f0d6.png)

**Comment by xiexianbin** [comment]
认领，有孚将对该bug进行修复

**Comment by shangtianfei** [comment]
文件：base_app.html.py
代码第59行依旧有误
![image](https://user-images.githubusercontent.com/24507317/57858214-3632d400-7823-11e9-8166-71691e34f0ae.png)

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/pull/117
