### ISSUE TITLE
我的应用-应用管理-环境变量title缺失

### ISSUE THREAD

**Issue by wklken** [Tencent/bk-PaaS#95]
页面位置: 我的应用 - 具体应用 - 应用管理 - 环境变量

问题描述: 缺失title / title高度、字体大小与基本信息页面保持一致

截图:

![image](https://user-images.githubusercontent.com/2002216/56647242-ba29ee00-66b3-11e9-896a-79ab8e135ccd.png)

期望

![image](https://user-images.githubusercontent.com/2002216/56647277-c910a080-66b3-11e9-8325-5731c08a11c2.png)

**Comment by canway-obama** [comment]
认领
