### ISSUE TITLE
我的应用-应用管理-基本信息-开发语言变更

### ISSUE THREAD

**Issue by wklken** [Tencent/bk-PaaS#96]
页面位置: 我的应用 - 应用管理 - 基本信息 - 开发语言

问题描述: 目前显示 `Python（Django 1.8）`,  而最新的5.1(devops_support分支), 使用的新的开发框架(2.0.0), 其`Django`版本是1.11

所以这里需要更新, 去掉 `Django`字样

截图:

![image](https://user-images.githubusercontent.com/2002216/56647846-bcd91300-66b4-11e9-9c6f-f80eff666f72.png)

**Comment by kindmakethewolrdpeace** [comment]
认领

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/pull/116
